New Features
firstandthird/provision pull request #1
Opened 2016-09-12 17:28 UTC by ecwillis

2016-09-12 17:51 UTC, jgallen23 commented on conf/default.yaml
> +  enabled: true
lets disable by default

2016-09-12 17:51 UTC, jgallen23 commented on conf/default.yaml
> +  enabled: true
disable by default

2016-09-12 17:52 UTC, jgallen23 commented on example/server.yaml
> +  SubnetId: 'subnet-4fefa02a'
why did you need this?

2016-09-12 17:52 UTC, jgallen23 commented on lib/create.js
> +    dns: (done) => {
eh?

2016-09-12 17:53 UTC, jgallen23 commented on lib/ec2.js
> +            this.config.server.keyName,
keypair is valid, why did this change?

2016-09-12 17:53 UTC, jgallen23 commented on lib/ec2.js
> +        const name = this.config.server.keyName;
same as above

2016-09-12 18:02 UTC, ecwillis commented on example/server.yaml
> +  SubnetId: 'subnet-4fefa02a'
This was for my account which doesn't have default subnet ids for the vpc. There is documentation out there somewhere, but if you don't include this - the command fails.

2016-09-12 18:10 UTC, jgallen23 commented on example/server.yaml
> +  SubnetId: 'subnet-4fefa02a'
lets remove from the example

2016-10-23 22:06 UTC, jgallen23 requested changes

2016-10-23 22:06 UTC, jgallen23 commented on lib/ec2.js
> +        this.route53.run(results.host, 'create', done);
we should add a way to disable this

2016-10-23 22:06 UTC, jgallen23 commented on example/server.yaml
> +    - 'jgallen'
not the right user

2016-10-23 22:06 UTC, jgallen23 commented on lib/route53.js
> +    async.auto({
should we check if its already set first?

2016-10-27 16:04 UTC, closed without merging